server:
  shutdown: graceful

eureka:
  instance:
    hostname: localhost

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  security:
    user:
      name: ${EUREKA_ID}
      password: ${EUREKA_PASSWORD}
  profiles:
    active: dev
