spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8761


eureka:
  instance:
    hostname: prod
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:
        http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@localhost:8762/eureka/